name:                cascade
version:             0.1.0.0
synopsis:            Stylesheets for prince
description:         See README.md
homepage:            https://github.com/dbaynard/cascade#readme
license:             Apache
author:              David Baynard
maintainer:          davidbaynard@gmail.com
copyright:           '2017'
category:            Publishing
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - errors

library:
  source-dirs: src
  dependencies:
  - clay >= 0.12.1
  - text
  - streaming
  - streaming-bytestring
  exposed-modules:
  - Cascade.Letter
  - Cascade.Print.Page
  - Cascade.Print.Prince

executables:
  cascade:
    source-dirs:      app
    main:             Main.lhs
    dependencies:
    - optparse-generic
    - cascade
