name:                cascade
version:             0.1.0.1
synopsis:            Stylesheets for prince
description:         See README.md
homepage:            https://github.com/dbaynard/cascade#readme
license:             Apache
author:              David Baynard
maintainer:          davidbaynard@gmail.com
copyright:           '2017'
category:            Publishing
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - errors

library:
  source-dirs: src
  dependencies:
  - clay >= 0.13.1
  - errors >= 2.2.1
  - text
  - streaming
  - streaming-with
  - streaming-bytestring
  exposed-modules:
  - Cascade
  - Cascade.Base
  - Cascade.Draft
  - Cascade.Git
  - Cascade.Github
  - Cascade.Letter
  - Cascade.Fonts
  - Cascade.Pandoc
  - Cascade.Rhythm
  - Cascade.Print.Page
  - Cascade.Print.Prince
  - Clay.Missing

build-tools:
  - markdown-unlit

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
#- -Wmissing-import-lists
- -Wcompat
- -Wnoncanonical-monad-instances
- -Wnoncanonical-monadfail-instances
- -pgmL markdown-unlit

executables:
  cascade:
    source-dirs: app
    main: app.lhs
    dependencies:
    - optparse-generic
    - cascade
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
